import Link from "next/link";

import type { Metadata } from "next";

export const metadata: Metadata = { title: "How Saelis uses AI" };

/** Honest, concise AI disclosure. */
export default function AiDisclosurePage() {
  return (
    <article className="mx-auto flex max-w-2xl flex-col gap-5">
      <h1 className="text-3xl font-semibold text-ink">How Saelis uses AI</h1>

      <section className="flex flex-col gap-2">
        <h2 className="text-lg font-semibold text-ink">Saelis is AI</h2>
        <p className="text-ink-soft">
          Every response you receive is generated by an artificial intelligence system — a large
          language model operating inside rules Saelis defines. Saelis is not a person, does not
          have feelings, and will never pretend to be human.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2 className="text-lg font-semibold text-ink">It can be wrong</h2>
        <p className="text-ink-soft">
          Saelis can misunderstand you, miss context, oversimplify, or state something incorrect. It
          does not truly comprehend emotions — it reads what you explicitly say and responds within
          careful rules. When it&apos;s uncertain, it is designed to say so. Please correct it
          freely, and don&apos;t treat anything it says as fact without checking.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2 className="text-lg font-semibold text-ink">Hard limits we enforce</h2>
        <p className="text-ink-soft">
          Saelis is built to never diagnose you, never claim your past caused your present, never
          guess at protected characteristics, never claim certainty about other people&apos;s
          motives, and never store anything lasting about you without your explicit approval. These
          aren&apos;t just instructions to the model — responses are checked and filtered by
          deterministic code after generation.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2 className="text-lg font-semibold text-ink">Not for emergencies</h2>
        <p className="text-ink-soft">
          Saelis is not therapy or a crisis service. If you may be in immediate danger, call 911. If
          you&apos;re in crisis, call or text 988 (US) to reach the Suicide &amp; Crisis Lifeline,
          any hour. When Saelis detects crisis language it will step out of ordinary conversation
          and point you to real help.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2 className="text-lg font-semibold text-ink">Where your words go</h2>
        <p className="text-ink-soft">
          To generate each response, your message and limited context are sent to our AI provider
          (OpenAI) over an encrypted connection, with storage and training use disabled on our API
          requests. Details are in{" "}
          <Link href="/privacy" className="underline decoration-accent-lilac underline-offset-4">
            Privacy
          </Link>
          .
        </p>
      </section>
    </article>
  );
}
